name: release

on:
  repository_dispatch:
    types: [build-successful]

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.client_payload.ref, 'refs/tags/v') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: orbatschow/kubepost
          tags: |
            type=semver,pattern={{version}}
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
